<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\models\Municipio;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Municipio::Create(['provincia_id'=>'99','nombre'=>'Porco']);
        Municipio::Create(['provincia_id'=>'100','nombre'=>'Arampampa']);
        Municipio::Create(['provincia_id'=>'100','nombre'=>'Acacio']);
        Municipio::Create(['provincia_id'=>'101','nombre'=>'Llica']);
        Municipio::Create(['provincia_id'=>'101','nombre'=>'Tahua']);
        Municipio::Create(['provincia_id'=>'102','nombre'=>'Villazon']);
        Municipio::Create(['provincia_id'=>'103','nombre'=>'San Agustin']);
        Municipio::Create(['provincia_id'=>'104','nombre'=>'Tarija']);
        Municipio::Create(['provincia_id'=>'105','nombre'=>'Padcaya']);
        Municipio::Create(['provincia_id'=>'105','nombre'=>'Bermejo']);
        Municipio::Create(['provincia_id'=>'106','nombre'=>'Yacuiba']);
        Municipio::Create(['provincia_id'=>'106','nombre'=>'Carapari']);
        Municipio::Create(['provincia_id'=>'106','nombre'=>'Villa Montes']);
        Municipio::Create(['provincia_id'=>'107','nombre'=>'Uriondo']);
        Municipio::Create(['provincia_id'=>'107','nombre'=>'Yunchara']);
        Municipio::Create(['provincia_id'=>'108','nombre'=>'San Lorenzo']);
        Municipio::Create(['provincia_id'=>'108','nombre'=>'El Puente']);
        Municipio::Create(['provincia_id'=>'109','nombre'=>'Entre Rios']);
        Municipio::Create(['provincia_id'=>'110','nombre'=>'Santa Cruz de la Sierra']);
        Municipio::Create(['provincia_id'=>'110','nombre'=>'Cotoca']);
        Municipio::Create(['provincia_id'=>'110','nombre'=>'Porongo']);
        Municipio::Create(['provincia_id'=>'110','nombre'=>'La Guardia']);
        Municipio::Create(['provincia_id'=>'110','nombre'=>'El Torno']);
        Municipio::Create(['provincia_id'=>'111','nombre'=>'Warnes']);
        Municipio::Create(['provincia_id'=>'111','nombre'=>'Okinawa']);
        Municipio::Create(['provincia_id'=>'112','nombre'=>'San Ignacio de Velasco']);
        Municipio::Create(['provincia_id'=>'112','nombre'=>'San Miguel de Velasco']);
        Municipio::Create(['provincia_id'=>'112','nombre'=>'San Rafael']);
        Municipio::Create(['provincia_id'=>'1','nombre'=>'Buena Vista']);
        Municipio::Create(['provincia_id'=>'1','nombre'=>'San Carlos']);
        Municipio::Create(['provincia_id'=>'1','nombre'=>'Yapacani']);
        Municipio::Create(['provincia_id'=>'1','nombre'=>'San Juan de Yapacani']);
        Municipio::Create(['provincia_id'=>'2','nombre'=>'San Jose de Chiquitos']);
        Municipio::Create(['provincia_id'=>'2','nombre'=>'Pailon']);
        Municipio::Create(['provincia_id'=>'2','nombre'=>'Robore']);
        Municipio::Create(['provincia_id'=>'3','nombre'=>'Portachuelo']);
        Municipio::Create(['provincia_id'=>'3','nombre'=>'Santa Rosa del Sara']);
        Municipio::Create(['provincia_id'=>'3','nombre'=>'Colpa Belgica']);
        Municipio::Create(['provincia_id'=>'4','nombre'=>'Lagunillas']);
        Municipio::Create(['provincia_id'=>'4','nombre'=>'Charagua']);
        Municipio::Create(['provincia_id'=>'4','nombre'=>'Cabezas']);
        Municipio::Create(['provincia_id'=>'4','nombre'=>'Cuevo']);
        Municipio::Create(['provincia_id'=>'4','nombre'=>'Gutierrez']);
        Municipio::Create(['provincia_id'=>'4','nombre'=>'Camiri']);
        Municipio::Create(['provincia_id'=>'4','nombre'=>'Boyuibe']);
        Municipio::Create(['provincia_id'=>'5','nombre'=>'Vallegrande']);
        Municipio::Create(['provincia_id'=>'5','nombre'=>'Trigal']);
        Municipio::Create(['provincia_id'=>'5','nombre'=>'Moro Moro']);
        Municipio::Create(['provincia_id'=>'5','nombre'=>'Postrer Valle']);
        Municipio::Create(['provincia_id'=>'5','nombre'=>'Pucara']);
        Municipio::Create(['provincia_id'=>'6','nombre'=>'Samaipata']);
        Municipio::Create(['provincia_id'=>'6','nombre'=>'Pampa Grande']);
        Municipio::Create(['provincia_id'=>'6','nombre'=>'Mairana']);
        Municipio::Create(['provincia_id'=>'6','nombre'=>'Quirusillas']);
        Municipio::Create(['provincia_id'=>'7','nombre'=>'Montero']);
        Municipio::Create(['provincia_id'=>'7','nombre'=>'General Saavedra']);
        Municipio::Create(['provincia_id'=>'7','nombre'=>'Mineros']);
        Municipio::Create(['provincia_id'=>'7','nombre'=>'Fernandez Alonso']);
        Municipio::Create(['provincia_id'=>'7','nombre'=>'San Pedro']);
        Municipio::Create(['provincia_id'=>'8','nombre'=>'Concepcion']);
        Municipio::Create(['provincia_id'=>'8','nombre'=>'San Javier']);
        Municipio::Create(['provincia_id'=>'8','nombre'=>'San Ramon']);
        Municipio::Create(['provincia_id'=>'8','nombre'=>'San Julian']);
        Municipio::Create(['provincia_id'=>'8','nombre'=>'San Antonio de Lomerio']);
        Municipio::Create(['provincia_id'=>'8','nombre'=>'Cuatro Cañadas']);
        Municipio::Create(['provincia_id'=>'9','nombre'=>'San Matias']);
        Municipio::Create(['provincia_id'=>'10','nombre'=>'Comarapa']);
        Municipio::Create(['provincia_id'=>'10','nombre'=>'Saipina']);
        Municipio::Create(['provincia_id'=>'11','nombre'=>'Puerto Suarez']);
        Municipio::Create(['provincia_id'=>'11','nombre'=>'Puerto Quijarro']);
        Municipio::Create(['provincia_id'=>'11','nombre'=>'Carmen Rivero Torrez']);
        Municipio::Create(['provincia_id'=>'12','nombre'=>'Ascencion de Guarayos']);
        Municipio::Create(['provincia_id'=>'12','nombre'=>'Urubicha']);
        Municipio::Create(['provincia_id'=>'12','nombre'=>'El Puente']);
        Municipio::Create(['provincia_id'=>'13','nombre'=>'Trinidad']);
        Municipio::Create(['provincia_id'=>'13','nombre'=>'San Javier']);
        Municipio::Create(['provincia_id'=>'14','nombre'=>'Riberalta']);
        Municipio::Create(['provincia_id'=>'14','nombre'=>'Guayaramerin']);
        Municipio::Create(['provincia_id'=>'15','nombre'=>'Reyes']);
        Municipio::Create(['provincia_id'=>'15','nombre'=>'San Borja']);
        Municipio::Create(['provincia_id'=>'15','nombre'=>'Santa Rosa']);
        Municipio::Create(['provincia_id'=>'15','nombre'=>'Rurrenabaque']);
        Municipio::Create(['provincia_id'=>'16','nombre'=>'Santa Ana']);
        Municipio::Create(['provincia_id'=>'16','nombre'=>'Exaltacion']);
        Municipio::Create(['provincia_id'=>'17','nombre'=>'San Ignacio']);
        Municipio::Create(['provincia_id'=>'18','nombre'=>'Loreto']);
        Municipio::Create(['provincia_id'=>'18','nombre'=>'San Andres']);
        Municipio::Create(['provincia_id'=>'19','nombre'=>'San Joaquin']);
        Municipio::Create(['provincia_id'=>'19','nombre'=>'San Ramon']);
        Municipio::Create(['provincia_id'=>'19','nombre'=>'Puerto Siles']);
        Municipio::Create(['provincia_id'=>'20','nombre'=>'Magdalena']);
        Municipio::Create(['provincia_id'=>'20','nombre'=>'Baures']);
        Municipio::Create(['provincia_id'=>'20','nombre'=>'Huaracaje']);
        Municipio::Create(['provincia_id'=>'21','nombre'=>'Cobija']);
        Municipio::Create(['provincia_id'=>'21','nombre'=>'Porvenir']);
        Municipio::Create(['provincia_id'=>'21','nombre'=>'Bolpebra']);
        Municipio::Create(['provincia_id'=>'21','nombre'=>'Bella Flor']);
        Municipio::Create(['provincia_id'=>'22','nombre'=>'Puerto Rico']);
        Municipio::Create(['provincia_id'=>'22','nombre'=>'San Pedro']);
        Municipio::Create(['provincia_id'=>'22','nombre'=>'Filadelfia']);
        Municipio::Create(['provincia_id'=>'23','nombre'=>'Puerto Gonzalo Moreno']);
        Municipio::Create(['provincia_id'=>'23','nombre'=>'San Lorenzo']);
        Municipio::Create(['provincia_id'=>'23','nombre'=>'Sena']);
        Municipio::Create(['provincia_id'=>'24','nombre'=>'Nacebe']);
        Municipio::Create(['provincia_id'=>'24','nombre'=>'Ingavi']);
        Municipio::Create(['provincia_id'=>'25','nombre'=>'Nuevo Manoa']);
        Municipio::Create(['provincia_id'=>'25','nombre'=>'Villa Nueva']);
        Municipio::Create(['provincia_id'=>'25','nombre'=>'Eureka']);
        Municipio::Create(['provincia_id'=>'26','nombre'=>'Sucre']);
        Municipio::Create(['provincia_id'=>'26','nombre'=>'Yotala']);
        Municipio::Create(['provincia_id'=>'26','nombre'=>'Poroma']);
        Municipio::Create(['provincia_id'=>'27','nombre'=>'Azurduy']);
        Municipio::Create(['provincia_id'=>'27','nombre'=>'Tarvita']);
        Municipio::Create(['provincia_id'=>'28','nombre'=>'Zudañez']);
        Municipio::Create(['provincia_id'=>'28','nombre'=>'Presto']);
        Municipio::Create(['provincia_id'=>'28','nombre'=>'Mojocoya']);
        Municipio::Create(['provincia_id'=>'28','nombre'=>'Icla']);
        Municipio::Create(['provincia_id'=>'29','nombre'=>'Padilla']);
        Municipio::Create(['provincia_id'=>'29','nombre'=>'Tomina']);
        Municipio::Create(['provincia_id'=>'29','nombre'=>'Sopachuy']);
        Municipio::Create(['provincia_id'=>'29','nombre'=>'Alcala']);
        Municipio::Create(['provincia_id'=>'29','nombre'=>'El villar']);
        Municipio::Create(['provincia_id'=>'30','nombre'=>'Monteagudo']);
        Municipio::Create(['provincia_id'=>'30','nombre'=>'Huacareta']);
        Municipio::Create(['provincia_id'=>'31','nombre'=>'Tarabuco']);
        Municipio::Create(['provincia_id'=>'31','nombre'=>'Yamparaez']);
        Municipio::Create(['provincia_id'=>'32','nombre'=>'Camargo']);
        Municipio::Create(['provincia_id'=>'32','nombre'=>'San lucas']);
        Municipio::Create(['provincia_id'=>'32','nombre'=>'Incahuasi']);
        Municipio::Create(['provincia_id'=>'32','nombre'=>'Villa Charcas']);
        Municipio::Create(['provincia_id'=>'33','nombre'=>'Villa Serrano']);
        Municipio::Create(['provincia_id'=>'34','nombre'=>'Camataqui (C. Villa abecia)']);
        Municipio::Create(['provincia_id'=>'34','nombre'=>'Culpina']);
        Municipio::Create(['provincia_id'=>'34','nombre'=>'Las Carreras']);
        Municipio::Create(['provincia_id'=>'35','nombre'=>'Villa Vaca Guzman (Muyupampa)']);
        Municipio::Create(['provincia_id'=>'35','nombre'=>'Huacaya (Villa de Huacaya)']);
        Municipio::Create(['provincia_id'=>'35','nombre'=>'Machareti']);
        Municipio::Create(['provincia_id'=>'36','nombre'=>'La Paz']);
        Municipio::Create(['provincia_id'=>'36','nombre'=>'Palca']);
        Municipio::Create(['provincia_id'=>'36','nombre'=>'Mecapaca']);
        Municipio::Create(['provincia_id'=>'36','nombre'=>'Achocalla']);
        Municipio::Create(['provincia_id'=>'36','nombre'=>'El Alto']);
        Municipio::Create(['provincia_id'=>'37','nombre'=>'Achacachi']);
        Municipio::Create(['provincia_id'=>'37','nombre'=>'Ancoraimes']);
        Municipio::Create(['provincia_id'=>'37','nombre'=>'Huarina']);
        Municipio::Create(['provincia_id'=>'37','nombre'=>'Santiago de Huata']);
        Municipio::Create(['provincia_id'=>'37','nombre'=>'Huatajata']);
        Municipio::Create(['provincia_id'=>'37','nombre'=>'Chua Cocani']);
        Municipio::Create(['provincia_id'=>'38','nombre'=>'Coro Coro']);
        Municipio::Create(['provincia_id'=>'38','nombre'=>'Caquiaviri']);
        Municipio::Create(['provincia_id'=>'38','nombre'=>'Calacoto']);
        Municipio::Create(['provincia_id'=>'38','nombre'=>'Comanche']);
        Municipio::Create(['provincia_id'=>'38','nombre'=>'Charaña']);
        Municipio::Create(['provincia_id'=>'38','nombre'=>'Waldo Ballivian']);
        Municipio::Create(['provincia_id'=>'38','nombre'=>'Nazacara de Pacajes']);
        Municipio::Create(['provincia_id'=>'38','nombre'=>'Santiago de Callapa']);
        Municipio::Create(['provincia_id'=>'39','nombre'=>'Puerto Acosta']);
        Municipio::Create(['provincia_id'=>'39','nombre'=>'Mocomoco']);
        Municipio::Create(['provincia_id'=>'39','nombre'=>'Puerto Carabuco']);
        Municipio::Create(['provincia_id'=>'39','nombre'=>'Humanata']);
        Municipio::Create(['provincia_id'=>'39','nombre'=>'Escoma']);
        Municipio::Create(['provincia_id'=>'40','nombre'=>'Chuma']);
        Municipio::Create(['provincia_id'=>'40','nombre'=>'Ayata']);
        Municipio::Create(['provincia_id'=>'40','nombre'=>'Aucapata']);
        Municipio::Create(['provincia_id'=>'41','nombre'=>'Sorata']);
        Municipio::Create(['provincia_id'=>'41','nombre'=>'Guanay']);
        Municipio::Create(['provincia_id'=>'41','nombre'=>'Tacacoma']);
        Municipio::Create(['provincia_id'=>'41','nombre'=>'Quiabaya']);
        Municipio::Create(['provincia_id'=>'41','nombre'=>'Combaya']);
        Municipio::Create(['provincia_id'=>'41','nombre'=>'Tipuani']);
        Municipio::Create(['provincia_id'=>'41','nombre'=>'Mapiri']);
        Municipio::Create(['provincia_id'=>'41','nombre'=>'Teoponte']);
        Municipio::Create(['provincia_id'=>'42','nombre'=>'Apolo']);
        Municipio::Create(['provincia_id'=>'42','nombre'=>'Pelechuco']);
        Municipio::Create(['provincia_id'=>'43','nombre'=>'Viacha']);
        Municipio::Create(['provincia_id'=>'43','nombre'=>'Guaqui']);
        Municipio::Create(['provincia_id'=>'43','nombre'=>'Tiawanacu']);
        Municipio::Create(['provincia_id'=>'43','nombre'=>'Desaguadero']);
        Municipio::Create(['provincia_id'=>'43','nombre'=>'San Andres de Machaca']);
        Municipio::Create(['provincia_id'=>'43','nombre'=>'Jesus de Machaca']);
        Municipio::Create(['provincia_id'=>'43','nombre'=>'Taraco']);
        Municipio::Create(['provincia_id'=>'44','nombre'=>'Luribay']);
        Municipio::Create(['provincia_id'=>'44','nombre'=>'Sapahaqui']);
        Municipio::Create(['provincia_id'=>'44','nombre'=>'Yaco']);
        Municipio::Create(['provincia_id'=>'44','nombre'=>'Malla']);
        Municipio::Create(['provincia_id'=>'44','nombre'=>'Cairoma']);
        Municipio::Create(['provincia_id'=>'45','nombre'=>'Inquisivi']);
        Municipio::Create(['provincia_id'=>'45','nombre'=>'Quime']);
        Municipio::Create(['provincia_id'=>'45','nombre'=>'Cajuata']);
        Municipio::Create(['provincia_id'=>'45','nombre'=>'Colquiri']);
        Municipio::Create(['provincia_id'=>'45','nombre'=>'Ichoca']);
        Municipio::Create(['provincia_id'=>'45','nombre'=>'Licoma Pampa']);
        Municipio::Create(['provincia_id'=>'46','nombre'=>'Chulumani']);
        Municipio::Create(['provincia_id'=>'46','nombre'=>'Irupana']);
        Municipio::Create(['provincia_id'=>'46','nombre'=>'Yanacachi']);
        Municipio::Create(['provincia_id'=>'46','nombre'=>'Palos Blancos']);
        Municipio::Create(['provincia_id'=>'46','nombre'=>'La Asunta']);
        Municipio::Create(['provincia_id'=>'47','nombre'=>'Pucarani']);
        Municipio::Create(['provincia_id'=>'47','nombre'=>'Laja']);
        Municipio::Create(['provincia_id'=>'47','nombre'=>'Batallas']);
        Municipio::Create(['provincia_id'=>'47','nombre'=>'Puerto Perez']);
        Municipio::Create(['provincia_id'=>'48','nombre'=>'Sica Sica']);
        Municipio::Create(['provincia_id'=>'48','nombre'=>'Umala']);
        Municipio::Create(['provincia_id'=>'48','nombre'=>'Ayo Ayo']);
        Municipio::Create(['provincia_id'=>'48','nombre'=>'Calamarca']);
        Municipio::Create(['provincia_id'=>'48','nombre'=>'Patacamaya']);
        Municipio::Create(['provincia_id'=>'48','nombre'=>'Colquencha']);
        Municipio::Create(['provincia_id'=>'48','nombre'=>'Collana']);
        Municipio::Create(['provincia_id'=>'49','nombre'=>'Coroico']);
        Municipio::Create(['provincia_id'=>'49','nombre'=>'Coripata']);
        Municipio::Create(['provincia_id'=>'50','nombre'=>'Ixiamas']);
        Municipio::Create(['provincia_id'=>'50','nombre'=>'San Buena Ventura']);
        Municipio::Create(['provincia_id'=>'51','nombre'=>'Charazani']);
        Municipio::Create(['provincia_id'=>'51','nombre'=>'Curva']);
        Municipio::Create(['provincia_id'=>'52','nombre'=>'Copacabana']);
        Municipio::Create(['provincia_id'=>'52','nombre'=>'San Pedro de Tiquina']);
        Municipio::Create(['provincia_id'=>'52','nombre'=>'Tito Yupanqui']);
        Municipio::Create(['provincia_id'=>'53','nombre'=>'San Pedro de Curahuara']);
        Municipio::Create(['provincia_id'=>'53','nombre'=>'Papel Pampa']);
        Municipio::Create(['provincia_id'=>'53','nombre'=>'Chacarilla']);
        Municipio::Create(['provincia_id'=>'54','nombre'=>'Santiago de Machaca']);
        Municipio::Create(['provincia_id'=>'54','nombre'=>'Catacora']);
        Municipio::Create(['provincia_id'=>'55','nombre'=>'Caranavi']);
        Municipio::Create(['provincia_id'=>'55','nombre'=>'Alto Beni']);
        Municipio::Create(['provincia_id'=>'56','nombre'=>'Cochabamba']);
        Municipio::Create(['provincia_id'=>'57','nombre'=>'Aiquile']);
        Municipio::Create(['provincia_id'=>'57','nombre'=>'Pasorapa']);
        Municipio::Create(['provincia_id'=>'57','nombre'=>'Omereque']);
        Municipio::Create(['provincia_id'=>'58','nombre'=>'Ayopaya']);
        Municipio::Create(['provincia_id'=>'58','nombre'=>'Morochata']);
        Municipio::Create(['provincia_id'=>'58','nombre'=>'Cocapata']);
        Municipio::Create(['provincia_id'=>'59','nombre'=>'Tarata']);
        Municipio::Create(['provincia_id'=>'59','nombre'=>'Anzaldo']);
        Municipio::Create(['provincia_id'=>'59','nombre'=>'Arbieto']);
        Municipio::Create(['provincia_id'=>'59','nombre'=>'Sacabamba']);
        Municipio::Create(['provincia_id'=>'60','nombre'=>'Arani']);
        Municipio::Create(['provincia_id'=>'60','nombre'=>'Vacas']);
        Municipio::Create(['provincia_id'=>'61','nombre'=>'Arque']);
        Municipio::Create(['provincia_id'=>'61','nombre'=>'Tacopaya']);
        Municipio::Create(['provincia_id'=>'62','nombre'=>'Capinota']);
        Municipio::Create(['provincia_id'=>'62','nombre'=>'Santivañes']);
        Municipio::Create(['provincia_id'=>'62','nombre'=>'Sicaya']);
        Municipio::Create(['provincia_id'=>'63','nombre'=>'Cliza']);
        Municipio::Create(['provincia_id'=>'63','nombre'=>'Toco']);
        Municipio::Create(['provincia_id'=>'63','nombre'=>'Tolata']);
        Municipio::Create(['provincia_id'=>'64','nombre'=>'Quillacollo']);
        Municipio::Create(['provincia_id'=>'64','nombre'=>'Sipe Sipe']);
        Municipio::Create(['provincia_id'=>'64','nombre'=>'Tiquipaya']);
        Municipio::Create(['provincia_id'=>'64','nombre'=>'Vinto']);
        Municipio::Create(['provincia_id'=>'64','nombre'=>'Colcapirhua']);
        Municipio::Create(['provincia_id'=>'65','nombre'=>'Sacaba']);
        Municipio::Create(['provincia_id'=>'65','nombre'=>'Colomi']);
        Municipio::Create(['provincia_id'=>'65','nombre'=>'Villa Tunari']);
        Municipio::Create(['provincia_id'=>'66','nombre'=>'Tapacari']);
        Municipio::Create(['provincia_id'=>'67','nombre'=>'Totora']);
        Municipio::Create(['provincia_id'=>'67','nombre'=>'Pojo']);
        Municipio::Create(['provincia_id'=>'67','nombre'=>'Pocona']);
        Municipio::Create(['provincia_id'=>'67','nombre'=>'Chimore']);
        Municipio::Create(['provincia_id'=>'67','nombre'=>'Puerto Villarroel']);
        Municipio::Create(['provincia_id'=>'67','nombre'=>'Entre Rios']);
        Municipio::Create(['provincia_id'=>'68','nombre'=>'Mizque']);
        Municipio::Create(['provincia_id'=>'68','nombre'=>'Vila Vila']);
        Municipio::Create(['provincia_id'=>'68','nombre'=>'Alalay']);
        Municipio::Create(['provincia_id'=>'69','nombre'=>'Punata']);
        Municipio::Create(['provincia_id'=>'69','nombre'=>'Villa Rivero']);
        Municipio::Create(['provincia_id'=>'69','nombre'=>'San Benito']);
        Municipio::Create(['provincia_id'=>'69','nombre'=>'Tacachi']);
        Municipio::Create(['provincia_id'=>'69','nombre'=>'Cuchumuela']);
        Municipio::Create(['provincia_id'=>'70','nombre'=>'Bolivar']);
        Municipio::Create(['provincia_id'=>'71','nombre'=>'Tiraque']);
        Municipio::Create(['provincia_id'=>'71','nombre'=>'Shinaota']);
        Municipio::Create(['provincia_id'=>'72','nombre'=>'Oruro']);
        Municipio::Create(['provincia_id'=>'72','nombre'=>'Caracollo']);
        Municipio::Create(['provincia_id'=>'72','nombre'=>'El Choro']);
        Municipio::Create(['provincia_id'=>'72','nombre'=>'Soracachi']);
        Municipio::Create(['provincia_id'=>'73','nombre'=>'Challapata']);
        Municipio::Create(['provincia_id'=>'73','nombre'=>'Santuario de Quillacas']);
        Municipio::Create(['provincia_id'=>'74','nombre'=>'Corque']);
        Municipio::Create(['provincia_id'=>'74','nombre'=>'Choque Cota']);
        Municipio::Create(['provincia_id'=>'75','nombre'=>'Curahuara de Carangas']);
        Municipio::Create(['provincia_id'=>'75','nombre'=>'Turco']);
        Municipio::Create(['provincia_id'=>'76','nombre'=>'Huachacalla']);
        Municipio::Create(['provincia_id'=>'76','nombre'=>'Escara']);
        Municipio::Create(['provincia_id'=>'76','nombre'=>'Cruz de Machacamarca']);
        Municipio::Create(['provincia_id'=>'76','nombre'=>'Yunguyo de Litoral']);
        Municipio::Create(['provincia_id'=>'76','nombre'=>'Esmeralda']);
        Municipio::Create(['provincia_id'=>'77','nombre'=>'Poopo']);
        Municipio::Create(['provincia_id'=>'77','nombre'=>'Pazña']);
        Municipio::Create(['provincia_id'=>'77','nombre'=>'Antequera']);
        Municipio::Create(['provincia_id'=>'78','nombre'=>'Huanuni']);
        Municipio::Create(['provincia_id'=>'78','nombre'=>'Machacamarca']);
        Municipio::Create(['provincia_id'=>'79','nombre'=>'Salinas de Garci Mendoza']);
        Municipio::Create(['provincia_id'=>'79','nombre'=>'Pampa Aullagas']);
        Municipio::Create(['provincia_id'=>'80','nombre'=>'Sabaya']);
        Municipio::Create(['provincia_id'=>'80','nombre'=>'Coipasa']);
        Municipio::Create(['provincia_id'=>'80','nombre'=>'Chipaya']);
        Municipio::Create(['provincia_id'=>'81','nombre'=>'Toledo']);
        Municipio::Create(['provincia_id'=>'82','nombre'=>'Eucaliptus']);
        Municipio::Create(['provincia_id'=>'83','nombre'=>'Andamarca']);
        Municipio::Create(['provincia_id'=>'83','nombre'=>'Belen de Andamarca']);
        Municipio::Create(['provincia_id'=>'84','nombre'=>'Totora']);
        Municipio::Create(['provincia_id'=>'85','nombre'=>'Santiago de Huari']);
        Municipio::Create(['provincia_id'=>'86','nombre'=>'La Rivera']);
        Municipio::Create(['provincia_id'=>'86','nombre'=>'Todos Santos']);
        Municipio::Create(['provincia_id'=>'86','nombre'=>'Carangas']);
        Municipio::Create(['provincia_id'=>'87','nombre'=>'Huayllamarca']);
        Municipio::Create(['provincia_id'=>'88','nombre'=>'Potosi']);
        Municipio::Create(['provincia_id'=>'88','nombre'=>'Tinguipaya']);
        Municipio::Create(['provincia_id'=>'88','nombre'=>'Yocalla']);
        Municipio::Create(['provincia_id'=>'88','nombre'=>'Belen de Urmiri']);
        Municipio::Create(['provincia_id'=>'89','nombre'=>'Uncia']);
        Municipio::Create(['provincia_id'=>'89','nombre'=>'Chayanta']);
        Municipio::Create(['provincia_id'=>'89','nombre'=>'Llallagua']);
        Municipio::Create(['provincia_id'=>'89','nombre'=>'Chuquihuta Ayllu Jucumani']);
        Municipio::Create(['provincia_id'=>'90','nombre'=>'Betanzos']);
        Municipio::Create(['provincia_id'=>'90','nombre'=>'Chaqui']);
        Municipio::Create(['provincia_id'=>'90','nombre'=>'Tacobamba']);
        Municipio::Create(['provincia_id'=>'91','nombre'=>'Colquechaca']);
        Municipio::Create(['provincia_id'=>'91','nombre'=>'Ravelo']);
        Municipio::Create(['provincia_id'=>'91','nombre'=>'Pocoata']);
        Municipio::Create(['provincia_id'=>'91','nombre'=>'Ocuri']);
        Municipio::Create(['provincia_id'=>'92','nombre'=>'San Pedro de Buena Vista']);
        Municipio::Create(['provincia_id'=>'92','nombre'=>'Toro Toro']);
        Municipio::Create(['provincia_id'=>'93','nombre'=>'Cotagaita']);
        Municipio::Create(['provincia_id'=>'93','nombre'=>'Vitichi']);
        Municipio::Create(['provincia_id'=>'94','nombre'=>'Sacaca']);
        Municipio::Create(['provincia_id'=>'94','nombre'=>'Caripuyo']);
        Municipio::Create(['provincia_id'=>'95','nombre'=>'Tupiza']);
        Municipio::Create(['provincia_id'=>'95','nombre'=>'Atocha']);
        Municipio::Create(['provincia_id'=>'96','nombre'=>'Colcha K']);
        Municipio::Create(['provincia_id'=>'96','nombre'=>'San Pedro de Quemes']);
        Municipio::Create(['provincia_id'=>'97','nombre'=>'San Pablo de Lipez']);
        Municipio::Create(['provincia_id'=>'97','nombre'=>'Mojinete']);
        Municipio::Create(['provincia_id'=>'97','nombre'=>'San Antonio de Esmoruco']);
        Municipio::Create(['provincia_id'=>'98','nombre'=>'Puna']);
        Municipio::Create(['provincia_id'=>'98','nombre'=>'Caiza D']);
        Municipio::Create(['provincia_id'=>'98','nombre'=>'Ckochas']);
        Municipio::Create(['provincia_id'=>'99','nombre'=>'Uyuni']);
        Municipio::Create(['provincia_id'=>'99','nombre'=>'Tomave']);

    }
}
