<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\models\Servicio;

class ServicioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Servicio::Create(['nombre'=>'Citoquímico de cualquier fluido (pleural, LCR, peritoneal, etc)','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'ANÁLISIS DE OTROS FLUIDOS CORPORALES']);
        Servicio::Create(['nombre'=>'Estudio anatomopatológico de cualquier pieza','precio'=>'100','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'ANATOMOPATOLOGÍA']);
        Servicio::Create(['nombre'=>'Tinción papanicolau','precio'=>'28','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'ANATOMOPATOLOGÍA']);
        Servicio::Create(['nombre'=>'Baciloscopía (incluye 2 tomas, tinción y lectura)','precio'=>'11','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'BACTERIOLOGÍA']);
        Servicio::Create(['nombre'=>'Coprocultivo','precio'=>'80','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'BACTERIOLOGÍA']);
        Servicio::Create(['nombre'=>'Cultivo para gérmenes comunes y antibiograma','precio'=>'80','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'BACTERIOLOGÍA']);
        Servicio::Create(['nombre'=>'Cultivo para tuberculosis','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'BACTERIOLOGÍA']);
        Servicio::Create(['nombre'=>'Determinación de concentración inhibitoria mínima para ATB','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'BACTERIOLOGÍA']);
        Servicio::Create(['nombre'=>'Diagnóstico de Bordetella','precio'=>'150','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'BACTERIOLOGÍA']);
        Servicio::Create(['nombre'=>'Frotis tinción Ghram','precio'=>'20','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'BACTERIOLOGÍA']);
        Servicio::Create(['nombre'=>'Hemocultivo y pruebas complementarias','precio'=>'180','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'BACTERIOLOGÍA']);
        Servicio::Create(['nombre'=>'Urocultivo','precio'=>'80','nivel'=>'II Nivel','financiamiento'=>'SUS','tipo'=>'BACTERIOLOGÍA']);
        Servicio::Create(['nombre'=>'Ferritina','precio'=>'30','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'DIAGNÓSTICO LABORATORIAL DE ANEMIA']);
        Servicio::Create(['nombre'=>'Transferrina','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'DIAGNÓSTICO LABORATORIAL DE ANEMIA']);
        Servicio::Create(['nombre'=>'Citograma nasal','precio'=>'15','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'HEMATOLOGÍA']);
        Servicio::Create(['nombre'=>'Estudio morfológico en médula ósea','precio'=>'30','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'HEMATOLOGÍA']);
        Servicio::Create(['nombre'=>'Frotis de sangre periferica','precio'=>'10','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'HEMATOLOGÍA']);
        Servicio::Create(['nombre'=>'Hemoglobina y hematocrito','precio'=>'20','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'HEMATOLOGÍA']);
        Servicio::Create(['nombre'=>'Hemograma completo','precio'=>'35','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'HEMATOLOGÍA']);
        Servicio::Create(['nombre'=>'Leucograma','precio'=>'20','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'HEMATOLOGÍA']);
        Servicio::Create(['nombre'=>'Recuento de reticulocitos','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'HEMATOLOGÍA']);
        Servicio::Create(['nombre'=>'Helicobacter pylori','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA FECAL']);
        Servicio::Create(['nombre'=>'Sangre oculta en heces','precio'=>'20','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA FECAL']);
        Servicio::Create(['nombre'=>'Anti dna','precio'=>'80','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Anticuerpo anti-tiroperoxidasa  por quimioluminiscencia anti-TPO','precio'=>'204','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Anticuerpos anticitoplasmaticos (ANCA)','precio'=>'80','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Anticuerpos anticitrulinados (anti CCP)','precio'=>'80','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Anticuerpos antifosfolipidos','precio'=>'80','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Anticuerpos antimicrosomales y antitiroglobulina','precio'=>'80','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Anticuerpos antinucleares ANA (IFI)','precio'=>'80','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Anticuerpos antireceptores de tsh por quimioluminiscencia - anti-RTSH','precio'=>'204','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Anticuerpos antitiroglobulina por quimioluminscencia anti-TG','precio'=>'204','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Anticuerpos monoclonales','precio'=>'300','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Grupo sanguíneo y factor Rh','precio'=>'30','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Identificación de células L.E.','precio'=>'20','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Prueba de coombs directa','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Prueba de coombs indirecta','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Antiestreptolisina O (ASTO)','precio'=>'45','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'C3','precio'=>'60','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'C4','precio'=>'60','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para anti HBC (anticore hepatitis B Ig M)','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para anti HBC (Anticore hepatitis B totales)','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para anticuerpos "E" de hepatitis B (Anti HBE)','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para anticuerpos de antígeno de superficie (anti HBS)','precio'=>'80','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para brucelosis Ig M','precio'=>'80','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para chagas','precio'=>'65','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para chlamydia','precio'=>'40','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para cisticercosis ','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para citomegalovirus Ig G','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para citomegalovirus Ig M','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para epstein barr virus Ig G','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para epstein barr virus Ig M','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para hantavirus','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para HBEAG (antígeno "E" hepatitis B)','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para HBSAG (antígeno de superficie - hepatitis B)','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para hepatitis A Ig M','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para hepatitis C','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'ELISA para herpes virus 1 Ig G','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para herpes virus 1 Ig M','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para herpes virus 1 y 2 Ig G','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para herpes virus 1 y 2 Ig M','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para herpes virus 2 Ig G','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para herpes virus 2 Ig M','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para leptospirosis','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para otras patologias','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para rubeola Ig M','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para sarampion IGG','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para sarampión Ig M','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para sífilis','precio'=>'40','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para torch','precio'=>'160','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para toxoplasmosis Ig M','precio'=>'180','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para varicela Ig G','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'ELISA para varicela Ig M','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Elisa para vih','precio'=>'55','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Factor reumatoideo','precio'=>'20','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'FTA para sífilis (inmunofluorescencia)','precio'=>'40','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Hemaglutinacion indirecta','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Ig G anti SARS CoV 2 (COVID-19) (ELISA)','precio'=>'150','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Ig G anti SARS CoV 2 (COVID-19) (quimioluminiscencia)','precio'=>'150','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Ig G/Ig M anti SARS CoV 2 (COVID-19) (prueba rápida)','precio'=>'60','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Ig M anti SARS CoV 2 (COVID-19) (ELISA)','precio'=>'150','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Ig M anti SARS CoV 2 (COVID-19) (quimioluminiscencia)','precio'=>'150','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Inhibidor del complemento C1','precio'=>'60','nivel'=>'II Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Inmunofluorescencia para chagas Ig G','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Inmunofluorescencia para chagas Ig M','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Inmunofluorescencia para leishmaniasis','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Inmunofluorescencia para virus respiratorios (Adenovirus, parainfluenza, sincitial respiratorio)','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Inmunoglobulinas IG A','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Inmunoglobulina A (Ig A) nefelometria','precio'=>'60','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Inmunoglobulina G  (Ig G) nefelometria','precio'=>'60','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Inmunoglobulina G (Ig G) IDR','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Inmunoglobulina M (Ig M) IDR','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'PCR (polimerasa de reacción de cadena) para leishmania','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'PCR (polimerasa de reacción de cadena) para tuberculosis','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'PCR (polimerasa de reacción en cadena) otros','precio'=>'150','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'PCR (polimerasa de reacción en cadena) para dengue','precio'=>'150','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'PCR (polimerasa de reacción en cadena) para fiebre amarilla','precio'=>'150','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'PCR (polimerasa de reacción en cadena) para H1N1','precio'=>'150','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'PCR (reacción en cadena de la polimerasa) para otros virus respiratorios','precio'=>'150','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'PPD','precio'=>'20','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'PROBNP','precio'=>'500','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Proteina c reactiva (PCR)','precio'=>'35','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Prueba rápida de diagnóstico para la detección del antígeno del SARS CoV 2','precio'=>'171','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Prueba rápida para dengue','precio'=>'30','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Prueba rápida para malaria','precio'=>'30','nivel'=>'I y II Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Prueba rápida para sífilis','precio'=>'30','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Prueba rápida para VIH/SIDA','precio'=>'30','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Reacción de Widal','precio'=>'33','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'RPR para sífilis-VDRL','precio'=>'15','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'RT PCR anti SARS CoV 2 (COVID-19) (PCR)','precio'=>'450','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Serología para chagas HAI','precio'=>'35','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Serología para dengue ELISA','precio'=>'60','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Serología para fiebre amarilla ELISA','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Serologia para hepatitis A','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Serologia para hepatitis B','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Serología para leishmania ELISA','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Serologia para rubeola ELISA','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'Serología para toxoplasmosis ELISA','precio'=>'60','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'INMUNOLOGÍA Y SEROLOGÍA']);
        Servicio::Create(['nombre'=>'AFP por quimioluminiscencia','precio'=>'155','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'Alfafetoproteina','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'Antígeno carcinoembrionario','precio'=>'80','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'B-HCG Libre por quimioluminiscencia','precio'=>'120','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'CA19-9','precio'=>'120','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'CA 125','precio'=>'120','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'Elisa para psa libre','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'Elisa para psa total','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'Prueba rápida para PSA','precio'=>'30','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'Psa total por quimioluminiscencia','precio'=>'127','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'PSA libre por quimioluminiscencia','precio'=>'127','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'MARCADORES TUMORALES']);
        Servicio::Create(['nombre'=>'Inmunodifusión para micosis','precio'=>'70','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'MICOLOGÍA']);
        Servicio::Create(['nombre'=>'Tinción para cristosporidium','precio'=>'15','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'MICOLOGÍA']);
        Servicio::Create(['nombre'=>'Tinción para hongos','precio'=>'15','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'MICOLOGÍA']);
        Servicio::Create(['nombre'=>'Cultivo micologico y fungigrama','precio'=>'85','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Cultivo para diagnostico de leptospirosis','precio'=>'150','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Diagnostico vih-western blot','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Eritrosedimentacion','precio'=>'10','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Examen micologico microscopico','precio'=>'35','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Factor antinuclear (FAN)','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Hsc (Tamizaje hiperplasia suprarrenal congenita 17 ohprg)','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Inmunofluorescencia indirecta','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Phmetría de 24 horas','precio'=>'1250','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Pp13 (Marcador de preeclampsia) rciu (Retraso de crecimiento intrauterino) app (Amenaza de parto preternino)','precio'=>'150','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Procesamiento de muestra de laboratorio (Adicional a prueba procesada) (SSCP)','precio'=>'26','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Reactantes de fase aguda (VES, fibrinogeno y PCR)','precio'=>'33','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Recuento de linfocitos  CD3/CD4 / CD8','precio'=>'250','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Tecnica de strout (Microhematocrito)','precio'=>'11','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Test de sudor para fibrosis quistica','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Prueba rápida con ácido acético o ácido sulfosalicílico','precio'=>'10','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'OTRAS PRUEBAS EN ORINA']);
        Servicio::Create(['nombre'=>'Coproparasitológico seriado','precio'=>'49','nivel'=>'I y II Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Coproparasitológico simple','precio'=>'15','nivel'=>'I y II Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Cultivo para leishmaniasis','precio'=>'80','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Examen en fresco','precio'=>'10','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Exámen parasitológico directo para leishmania frotis','precio'=>'15','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Gota gruesa y frotis sanguíneo + tinción (malaria)','precio'=>'10','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Investigación de filaria','precio'=>'20','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Micrométodo de concentración para chagas Strout','precio'=>'20','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Moco fecal','precio'=>'11','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Prueba de strout para chagas','precio'=>'20','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Prueba rápida para chagas','precio'=>'30','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Reacción de Weil Felix','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Separación de larvas de strongiloides (método de Baerman)','precio'=>'15','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Técnica de Graham','precio'=>'10','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PARASITOLOGÍA']);
        Servicio::Create(['nombre'=>'Creatina kinasa-CK','precio'=>'35','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL CARDIACO']);
        Servicio::Create(['nombre'=>'Creatina kinasa-MB','precio'=>'55','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL CARDIACO']);
        Servicio::Create(['nombre'=>'LDH deshidrogenasa láctica','precio'=>'35','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL CARDIACO']);
        Servicio::Create(['nombre'=>'Troponina i','precio'=>'58','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL CARDIACO']);
        Servicio::Create(['nombre'=>'Calcio total','precio'=>'35','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL DE ELECTROLITOS']);
        Servicio::Create(['nombre'=>'Electrolitos en sangre (Sodio, potasio y cloro)','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL DE ELECTROLITOS']);
        Servicio::Create(['nombre'=>'Fosfatemia (fósforo en sangre)','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL DE ELECTROLITOS']);
        Servicio::Create(['nombre'=>'Magnesemia','precio'=>'20','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL DE ELECTROLITOS']);
        Servicio::Create(['nombre'=>'Dimero-D','precio'=>'200','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HEMOSTASIA']);
        Servicio::Create(['nombre'=>'Fibrinógeno','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HEMOSTASIA']);
        Servicio::Create(['nombre'=>'Recuento de plaquetas','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HEMOSTASIA']);
        Servicio::Create(['nombre'=>'Tiempo de coagulación y tiempo de sangría','precio'=>'10','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HEMOSTASIA']);
        Servicio::Create(['nombre'=>'Tiempo de protrombina','precio'=>'35','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HEMOSTASIA']);
        Servicio::Create(['nombre'=>'Tiempo de sangría y recalcificación','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HEMOSTASIA']);
        Servicio::Create(['nombre'=>'Tiempo de protrombina (TPP)','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Tiempo parcial de tromboplastina activada','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HEMOSTASIA']);
        Servicio::Create(['nombre'=>'Albúmina','precio'=>'25','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HEPÁTICO']);
        Servicio::Create(['nombre'=>'Bilirrubinas totales y fracciones','precio'=>'35','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HEPÁTICO']);
        Servicio::Create(['nombre'=>'Fosfatasa alcalina','precio'=>'35','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HEPÁTICO']);
        Servicio::Create(['nombre'=>'ACTH','precio'=>'60','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'Cortisol plasmático (2 muestras)','precio'=>'60','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'Gonadotrofina coriónica humana (HCG)/test de embarazo en sangre','precio'=>'15','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'Hormona del crecimiento humana por quimioluminiscencia - hGH','precio'=>'86','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'Perfil hormonal hipofisiario/talamico','precio'=>'86','nivel'=>'II Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'Progesterona por quimioluminiscencia','precio'=>'81','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'T3','precio'=>'40','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'T3 total por quimioluminiscencia','precio'=>'64','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'T4 libre','precio'=>'40','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'T4 libre por quimioluminiscencia','precio'=>'74','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'T4 total','precio'=>'40','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'T4 total por quimioluminiscencia','precio'=>'64','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'Tsh','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'Tsh us por quimioluminiscencia','precio'=>'64','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL HORMONAL']);
        Servicio::Create(['nombre'=>'Colesterol','precio'=>'35','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL LIPÍDICO']);
        Servicio::Create(['nombre'=>'HDL - LDL - VLDL','precio'=>'20','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL LIPÍDICO']);
        Servicio::Create(['nombre'=>'Amilasa pancreática','precio'=>'25','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL METABÓLICO']);
        Servicio::Create(['nombre'=>'Creatinina sérica','precio'=>'35','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL METABÓLICO']);
        Servicio::Create(['nombre'=>'Glicemia ','precio'=>'35','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL METABÓLICO']);
        Servicio::Create(['nombre'=>'Glicemia postprandial ','precio'=>'60','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL METABÓLICO']);
        Servicio::Create(['nombre'=>'Hemoglobina glicosilada (HBA A 1C)','precio'=>'70','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL METABÓLICO']);
        Servicio::Create(['nombre'=>'Lipasa sérica','precio'=>'25','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL METABÓLICO']);
        Servicio::Create(['nombre'=>'Proteínas totales','precio'=>'22','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL METABÓLICO']);
        Servicio::Create(['nombre'=>'Prueba de tolerancia a la glucosa (5 mediciones)','precio'=>'100','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL METABÓLICO']);
        Servicio::Create(['nombre'=>'Creatinina en orina','precio'=>'35','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL RENAL']);
        Servicio::Create(['nombre'=>'Exámen general de orina más sedimento','precio'=>'20','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL RENAL']);
        Servicio::Create(['nombre'=>'Glucosuria','precio'=>'15','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL RENAL']);
        Servicio::Create(['nombre'=>'Morfología de glóbulos rojos en orina','precio'=>'10','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL RENAL']);
        Servicio::Create(['nombre'=>'Nitrógeno uréico sérico','precio'=>'20','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL RENAL']);
        Servicio::Create(['nombre'=>'Proteinuria de 24 horas','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL RENAL']);
        Servicio::Create(['nombre'=>'Úrea','precio'=>'15','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PERFIL RENAL']);
        Servicio::Create(['nombre'=>'Duo de maternidad (BHCG libre y PAPP-A marcador síndrome de Down)','precio'=>'200','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'PRUEBAS DE TAMIZAJE']);
        Servicio::Create(['nombre'=>'IRT (tamizaje fibrosis quística IRT)','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PRUEBAS DE TAMIZAJE']);
        Servicio::Create(['nombre'=>'Pku tamizaje de fenilcetonuria (Fenilalanina)','precio'=>'60','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PRUEBAS DE TAMIZAJE']);
        Servicio::Create(['nombre'=>'TSH-N (tamizaje neonatal de hipotiroidismo congénito)','precio'=>'50','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PRUEBAS DE TAMIZAJE']);
        Servicio::Create(['nombre'=>'Control de calidad de muestra de leche humana en banco de leche materna','precio'=>'81','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'PRUEBAS ESPECIALES']);
        Servicio::Create(['nombre'=>'Test de úreasa ','precio'=>'60','nivel'=>'II Nivel','financiamiento'=>'SUS','tipo'=>'PRUEBAS ESPECIALES']);
        Servicio::Create(['nombre'=>'Toma de muestra para RT PCR COVID-19 (Hisopeado faringeo)','precio'=>'100','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'PRUEBAS ESPECIALES']);
        Servicio::Create(['nombre'=>'Ácido úrico','precio'=>'30','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Alcoholemia y otras sustancias en sangre','precio'=>'10','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Amoniaco sérico','precio'=>'20','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Electroforesis de proteinas','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Fosfatasa ácida','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Fosfatasa ácida prostática','precio'=>'30','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Fosfatidilglicerol','precio'=>'30','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Gasometría arterial o venosa','precio'=>'80','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Índice lecitina/esfingomielina','precio'=>'30','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Lactato sérico','precio'=>'30','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Niveles de vitamina B1, B12 y ácido fólico','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Niveles de vitamina B12','precio'=>'50','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Transaminasa TGO','precio'=>'25','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Transaminasa TGP','precio'=>'27','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Trigliceridos','precio'=>'40','nivel'=>'I, II y III Nivel','financiamiento'=>'SUS','tipo'=>'QUÍMICA SANGUÍNEA']);
        Servicio::Create(['nombre'=>'Carga viral','precio'=>'10','nivel'=>'II y III Nivel','financiamiento'=>'SUS','tipo'=>'NINGUNO']);
        Servicio::Create(['nombre'=>'Carga viral para hepatitis  B','precio'=>'850','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'VIROLOGÍA']);
        Servicio::Create(['nombre'=>'Virología biológica molecular citogénetica','precio'=>'300','nivel'=>'III Nivel','financiamiento'=>'SUS','tipo'=>'VIROLOGÍA']);



    }
}
